### ISSUE TITLE
Failed to execute 'copyExternalImageToTexture' on 'GPUQueue': Copy rect is out of bounds of external image

### ISSUE THREAD

**Issue by UstymUkhman** [GPU-Gang/WebGPU-Erosion-Simulation#15]
Hi! Really nice project over here. Unfortunately it's not possible to preview it at the moment because of the error in the title.

![error](https://github.com/GPU-Gang/WebGPU-Erosion-Simulation/assets/9247261/f1f0dc5c-a8d3-4ee9-b552-5c51de758914)

**Comment by thecapablesnakekeeper** [comment]
Thank you for pointing it out, it should be fixed now! We are still working actively on this project and need to add/fix a lot of features, but happy for any feedback you have for us!
